### ISSUE TITLE
Floor 5 crashing due to Cowlection mod

### ISSUE THREAD

**Issue by minsikshin** [cow-mc/Cowlection#2]
I'm not a programmer so can't be sure but I think your mod is causing issues with the new dungeons floor 5. I crash soon after I join the dungeon.
[crash-2020-09-17_19.01.53-client.txt](https://github.com/cow-mc/Cowlection/files/5242406/crash-2020-09-17_19.01.53-client.txt)

**Comment by cow-mc** [comment]
You're still using version 0.10.1 and the crash has already been fixed in https://github.com/cow-mc/Cowlection/commit/705299e37d27d421156a09213e0654d0ab4fb01c.
Update to [version 0.10.2](https://github.com/cow-mc/Cowlection/releases/download/v1.8.9-0.10.2/Cowlection-1.8.9-0.10.2.jar).
